spring:
  application:
    name: finpay-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/finpay
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: finpaySuperSecureJwtSecretKey2026BackendAuthSystem
  expiration: 3600000